### ISSUE TITLE
Hi Please help

### ISSUE THREAD

**Issue by 74981** [JeeveshN/Facial-Recognition-Tool#9]
-MAC:Facial-Recognition-Tool-master 2 b0074981$ python face_recog.py "1.jpeg"
Traceback (most recent call last):
  File "face_recog.py", line 12, in <module>
    Datafile = shelve.open("Data")
  File "/anaconda3/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/anaconda3/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/anaconda3/lib/python3.7/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined-MAC:Facial-Recognition-Tool-master 2$

**Comment by JeeveshN** [comment]
@74981 Run it using python2.7
